# Generated by Django 2.2.2 on 2019-06-29 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
