# Generated by Django 2.2.2 on 2019-07-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_name', models.CharField(max_length=120)),
                ('cust_email', models.EmailField(max_length=120)),
                ('cust_phone', models.CharField(max_length=10)),
                ('cust_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=120)),
                ('item_ids', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_img_path', models.CharField(max_length=255, null=True)),
                ('item_id', models.IntegerField(null=True)),
                ('item_name', models.CharField(max_length=50, null=True)),
                ('item_qty', models.PositiveIntegerField(null=True)),
                ('item_price', models.PositiveIntegerField(null=True)),
                ('status', models.CharField(default='Not Cleaned', max_length=30, null=True)),
            ],
        ),
    ]
