# Generated by Django 2.2.2 on 2019-07-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='item_qtys',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
