# Generated by Django 2.2.2 on 2019-07-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_customer_added_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmetrics',
            name='revenue_today',
        ),
        migrations.AddField(
            model_name='salesmetrics',
            name='user_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
