# Generated by Django 2.2.2 on 2019-07-12 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190713_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeritems',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
